### PR TITLE
[POAE7-2767] Fix memory leak in LLVMIfBuilder

### PR DESCRIPTION
**Pull request by bigPYJ1151**
### What changes were proposed in this pull request?

Fix memory leak in LLVMIfBuilder

### Why are the changes needed?

BugFix

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UTs

### Which label does this PR belong to?

BugFix

### CODE REVIEW

**Review by winningsix — APPROVED** [review]
Great catch. Need to add some test cases to cover this?

**Comment by kd97** [comment]
bug fixed in my test. q: no need change to `LLVMLoopBuilder`?

**Review by kd97 — APPROVED** [review]

**Comment by bigPYJ1151** [comment]
> Great catch. Need to add some test cases to cover this?

Currently address sanitizer is disabled in CI because of some existing memory problems, maybe we should fix them and enable address sanitizer by default.

**Comment by bigPYJ1151** [comment]
> bug fixed in my test. q: no need change to `LLVMLoopBuilder`?

```LoopBuilder``` is fine.

**Pull request merged**
