### PR TITLE
[POAE7-2788] Add java support for ICL

### PR DESCRIPTION
**Pull request by xieqi**
### What changes were proposed in this pull request?

Add java support

### Why are the changes needed?

Add java support

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Just an empty project, no UT need.

### Which label does this PR belong to?

INFRA

### CODE REVIEW

**Review by winningsix — COMMENTED** [review]
Need an intro about project structure in https://intel.github.io/BDTK/develop/debugging.html#how-to-contribute?

**Comment by chaojun-zhang** [comment]
rename folder 'java' to  'jvm', since we may have other languages support in future?

**Review by chaojun-zhang — DISMISSED** [review]

**Review by kyotoyx — APPROVED** [review]

**Comment by harborn** [comment]
I think its unnecessary to make a new directory `cpp`: all cpp codes' depth is too deep.

**Comment by xieqi** [comment]
> I think its unnecessary to make a new directory `cpp`: all cpp codes' depth is too deep.

we follow arrow's specification, directory structure by language

**Review by harborn — DISMISSED** [review]
unnecessary make a new directory `cpp` to store all cpp files

**Comment by xieqi** [comment]
> unnecessary make a new directory `cpp` to store all cpp files
 
store all cpp files under cpp/src folder, then categorized by each project module

store all java/scala files under jvm folder

**Review by chaojun-zhang — APPROVED** [review]
lgtm

**Review by Ma-Jian1 — APPROVED** [review]

**Pull request merged**
