### PR TITLE
[POAE7-2845]The date type in the query is converted to cast as varchar

### PR DESCRIPTION
**Pull request by PenghuiJiao**
### What changes were proposed in this pull request?

The date type in the query is converted to cast as varchar

### Why are the changes needed?

nightly test failed
velox does not support the date type, and the date type is stored as a varchar type in hadoop, so the date type in the query needs to be converted to the varchar type.
After velox supports the date type, the date-varchar type in hadoop and query needs to be changed back to the date type.
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

cicd
### Which label does this PR belong to?

cicd

### CODE REVIEW

**Comment by winningsix** [comment]
Is this required by Presto?

**Comment by jikunshang** [comment]
1. what's the root cause of this issue? from your description, `cast as varchar` is your solution, right?
2. any performance drop issue if you change query?

**Comment by PenghuiJiao** [comment]
> 1. what's the root cause of this issue? from your description, `cast as varchar` is your solution, right?
> 2. any performance drop issue if you change query?

velox does not support storing the date type, and now convert the date type to varchar type when storing

**Comment by PenghuiJiao** [comment]
> Is this required by Presto?

Yes, velox does not support date type

**Review by harborn — APPROVED** [review]

**Review by kyotoyx — APPROVED** [review]

**Pull request merged**
