### PR TITLE
[POAE7-2584] Enable Arrow data format in output convertor leveraging Velox Arrow bridge

### PR DESCRIPTION
**Pull request by YantingTao1315**
### What changes were proposed in this pull request?
+  supply data format convert method in stateless operator
+ fix some logical error 

### Why are the changes needed?
+ new data format usage

### Does this PR introduce _any_ user-facing change?
+ No

### How was this patch tested?
+ UTs - use flag ```--use_cider_data_format```

### Which label does this PR belong to?
INFRA

### CODE REVIEW

**Comment by YantingTao1315** [comment]
Arrow data format convert supplement @kyotoyx @harborn , any comment ?

**Comment by jikunshang** [comment]
> Arrow data format convert supplement @kyotoyx @harborn , any comment ?

If we want to enable arrow format path, we need execute command like `./cider-velox/test/CiderOperatorTest --use_cider_data_format`. Any suggestion to change CI scripts?

**Review by Ma-Jian1 — APPROVED** [review]

**Review by winningsix — DISMISSED** [review]

**Review by Ma-Jian1 — APPROVED** [review]

**Review by winningsix — APPROVED** [review]

**Comment by jikunshang** [comment]
I think this PR didn't enable arrow format test path in CI.

**Comment by YantingTao1315** [comment]
> I think this PR didn't enable arrow format test path in CI.

Yes，if we want to enable it in CI, we should add flags in cmkelist like this:
image

**Pull request merged**
