### PR TITLE
[POAE7-2260] add more test for coalesce

### PR DESCRIPTION
**Pull request by yma11**
### What changes were proposed in this pull request?
add more test for coalesce syntax, reorg existing TCs

### Why are the changes needed?
test feature

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Review by jikunshang — APPROVED** [review]

**Review by jikunshang — COMMENTED** [review]
Please fix lint issues.

**Comment by yma11** [comment]
> Please fix lint issues.

I use the format tool directly, so we may need update the tool?

**Comment by yma11** [comment]
> > Please fix lint issues.
> 
> I use the format tool directly, so we may need update the tool?

Seems the tool doesn't handle the line length of `#define`, let me update it manually.

**Comment by jikunshang** [comment]
> > > Please fix lint issues.
> > 
> > 
> > I use the format tool directly, so we may need update the tool?
> 
> Seems the tool doesn't handle the line length of `#define`, let me update it manually.

ide build-in formatter may work:)

**Review by spevenhe — APPROVED** [review]
LGTM

**Review by jikunshang — APPROVED** [review]

**Pull request merged**
