### PR TITLE
[POAE7-2424] Arrow Support for FunctionOper

### PR DESCRIPTION
**Pull request by yma11**
### What changes were proposed in this pull request?
Arrow Support for FunctionOper

### Why are the changes needed?
support FunctionOper with Arrow format

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
UT

### CODE REVIEW

**Review by jikunshang — DISMISSED** [review]
Please rebase to resolve conflict.

**Review by jikunshang — DISMISSED** [review]

**Comment by yma11** [comment]
@winningsix @bigPYJ1151 Can you help take a review on this PR. Thanks.

**Review by bigPYJ1151 — DISMISSED** [review]
Overall looks good, but the logic is a little bit obscure because most from original implementation😂Maybe could refactor them further.

**Comment by yma11** [comment]
> Overall looks good, but the logic is a little bit obscure because most from original implementation😂Maybe could refactor them further.

Yes. I just removed the unused lines in this part since I think most of the original logic is still meaningful when we support more cases of functionOp in future. Of course we will do refactor if needed. Thanks for review!

**Review by bigPYJ1151 — APPROVED** [review]

**Review by jikunshang — APPROVED** [review]

**Pull request merged**
