### PR TITLE
[POAE7-2403] [WIP] Enabled Parquet format data in CICD. 

### PR DESCRIPTION
**Pull request by kyotoyx**
### What changes were proposed in this pull request?

Commented queries that not supported in current version. 

### Why are the changes needed?

To enable parquet format. 

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

CICD

### Which label does this PR belong to?

CICD

### CODE REVIEW

**Review by harborn — APPROVED** [review]

**Comment by winningsix** [comment]
Sounds like Parquet format will fail a lot of test cases? Any possibility we enable both dwrf format and Parquet format for short term and deprecate dwrf format once Parquet getting mature. Your thoughts?

**Comment by kyotoyx** [comment]
> Sounds like Parquet format will fail a lot of test cases? Any possibility we enable both dwrf format and Parquet format for short term and deprecate dwrf format once Parquet getting mature. This is to keep current test coverage.
> 
> Your thoughts?
Most of the failing cases are caused by Velox Parquet reader. To support those cases we might do some research to find out if these problem can be solved easily. And if not, we might wait an uncertain period time for the upstream supporting. 
So my suggesting is that, we need to do a minor research (0.5~2 days at most) then decide which format to use in our CICD.

**Comment by winningsix** [comment]
Just to confirm, the merge criteria for this PR is to pass all nightly test, right?

**Comment by jikunshang** [comment]
should we close this?

**Pull request closed without merging**
